### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Lemez** [lpil/cheep#1]

**Comment by lpil** [comment]
If I was smart I would have put something in the readme...

```
louis ~ $ gem install cheep
  Successfully installed cheep-0.0.4
  Parsing documentation for cheep-0.0.4
  Done installing documentation for cheep after 0 seconds
  1 gem installed
louis ~ $ irb
2.1.1 :001 > require 'cheep'
  Cheep cheep!
  => true 
2.1.1 :002 > Cheep.play Cheep::Sine.new(440, 80000).samples
  Playing WAVE 'cheep.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
  => true
```

**Comment by lpil** [comment]
Note this probably won't be correct for very long. I've not decided how this should work really.

**Comment by Lemez** [comment]
Wanna join in this?

https://www.eventbrite.com/e/hackathon-at-techcrunch-disrupt-eu-2014-london-tickets-12058193381

**Comment by lpil** [comment]
Wow, that sounds pretty cool. I've never done anything like that before. Are you supposed to have a team and a project prepared?

edit: I've signed up. :)

**Comment by Lemez** [comment]
Cool. Am going with our senior rails man Cosimo. Wanna be in our gang?

**Comment by lpil** [comment]
Yes, though I might have told them that I'm not going. Ah I'm sure it'll be
fine.

Have we got a project? Do I need to register as part of your group
somewhere?
